### ISSUE TITLE
Processing/value date switch

### ISSUE THREAD

**Issue by eherle** [gbonnema/rabo2ofx#5]
Testing the script I ran into a problem with the reconciliation. In my current workflow I import a month of transactions and reconcile the account to match the account statement of the Rabobank. This runs smoothly. After import the new balance amount always equals the ending balance of the statement. This workflow is in line with the [format description of the Rabobank](https://www.rabobank.nl/images/formatdescription-csv-extension_29939190.pdf) and their email response ([01-datum-20180410-Uw-klacht.txt](https://github.com/gbonnema/rabo2ofx/blob/master/response-datum-rabo/01-datum-20180410-Uw-klacht.txt)). It may not be 100% in line with accounting principles, but it works very well for me.

However, the reconciliation of my test run failed because there was a transaction with a different processing and value date. As documented, this script uses the value date (interest date) instead of the processing date. This unfortunately prevents matching ending balances in case these dates are in separate months.

It would be great if this script can be used to reconcile imports per month as described above. Is it possible to add an option to this script that enables the user to choose the processing date or the value/interest date as the date for the transaction in the ofx file (\<DTPOSTED\>)?

**Comment by gbonnema** [comment]
Personally, I do not like the option, but I understand you want your monthly statements to coincide with the bank statement. I will have a look as soon as I have some spare time. In the meantime you could change one line where I use "keyInterestDate" into "keyDate" on line 353. That should be a workaround for now until I get around to changing it. You should realize though that this might change the fitid where I use dtposted (was interest date, will be date) which might interfere with past bookings. Fitid exists to prevent double bookings. A different fitid means a different booking. 
I will let you know when I added the option.

**Comment by eherle** [comment]
Great! In the meantime, I will update the date manually in Gnucash or (de)select the transaction in the reconciliation overview. Since 'I have not eaten any cheese' 😉 from python, it is not wise to touch the code myself...

**Comment by gbonnema** [comment]
Fair enough. I will let you know when I changed stuff.

**Comment by gbonnema** [comment]
I uploaded version 2.14, but I urge you to test. I suspect you are the only one using the override, so it better be perfect. For testing you could create a new directory and copy some of your production files to test. You can visually see in the ofx file if you get the expected overrides, and after processing, in Gnucash.

Don't forget to change your config file (the example file shows how).

Let me know, if you think everything is correct so I can close the issue.

**Comment by eherle** [comment]
Tested it and it works fine. Thank you.
